### PR TITLE
Add static masterLogger, allows for multiple logger instances on master

### PR DESCRIPTION
**Pull request by zerote000**
Add static masterLogger, allows for multiple logger instances on master thread with only one instance logging to console or file.

This fixes an issue with winston-daily-rotate-file, which does not support multiple logger instances, and only logs from one instance will be written to file after the first file split.

### CODE REVIEW

**Comment by ryankurte** [comment]
looks good to me! how would you feel about calling it `BaseLogger`?

**Comment by zerote000** [comment]
Sure, works for me :)

**Comment by zerote000** [comment]
Not sure if it pings you when I add commits to the PR, but I made the change :)

**Comment by ryankurte** [comment]
looks great, thanks! i am happy to keep reviewing / maintaining things but, haven't actually had to deploy this in some years, if you're gettin use out of it would you like to be added as a maintainer here and on npm?

**Comment by zerote000** [comment]
Sure :)
Username on npm is the same as here on GitHub

**Pull request merged**
